const items =[
    {title: " Petrichor", tag:['all', 'sculptist'],img: "images/card40 (2).jpeg",link: "page1.html"},
    {title: " Fernweh", tag:['all', 'sculptist'],img: "images/card3.jpeg",link: "page1.html"},
    {title: " Sobremesa", tag:['all', 'sculptist'],img: "images/card4.jpeg",link: "page1.html"},
    {title: " hello", tag:['all', 'sculptist'],img: "images/card5.jpeg",link: "page1.html"},
    {title: " Duende", tag:['all', 'sculptist'],img: "images/card6.jpeg",link: "page1.html"},
    {title: " Wabi-Sabi", tag:['all', 'sculptist'],img: "images/card7.jpeg",link: "page1.html"},
    {title: " Ethereal", tag:['all', 'sculptist'],img: "images/card9.jpeg",link: "page1.html"},
    {title: " Ephemeral", tag:['all', 'sculptist'],img: "images/card10.jpeg",link: "page1.html"},
    {title: " Stellify", tag:['all', 'sculptist'],img: "images/card11.jpeg",link: "page1.html"},
    {title: " Lagom", tag:['all', 'sculptist'],img: "images/card12.jpeg",link: "page1.html"},
    {title: " Shanti", tag:['all', 'sculptist'],img: "images/card13.jpeg",link: "page1.html"},
    {title: " Jugaad", tag:['all', 'sculptist'],img: "images/card14.jpeg",link: "page1.html"},
    {title: " Toska", tag:['all', 'sculptist'],img: "images/card17.jpeg",link: "page1.html"},
    {title: " Barakah", tag:['all', 'serenist'],img: "images/card18.jpeg",link: "page1.html"},
    {title: " Inshallah", tag:['all', 'serenist'],img: "images/card19.jpeg",link: "page1.html"},
    {title: " Iktsuarpok", tag:['all', 'serenist'],img: "images/card21.jpeg",link: "page1.html"},
    {title: " Fika", tag:['all', 'serenist'],img: "images/card20.jpeg",link: "page1.html"},
    {title: " Eudaimonia", tag:['all', 'serenist'],img: "images/card22.jpeg",link: "page1.html"},
    {title: " Tadhana", tag:['all', 'serenist'],img: "images/card23.jpeg",link: "page1.html"},
    {title: " Kilig", tag:['all', 'serenist'],img: "images/card24.jpeg",link: "page1.html"},
    {title: " Philoxenia", tag:['all', 'serenist'],img: "images/card25.jpeg",link: "page1.html"},
{title: " Dolce far niente", tag:['all', 'serenist'],img: "images/card26.jpeg",link: "page1.html"},
{title: " Saudade", tag:['all', 'serenist'],img: "images/card27.jpeg",link: "page1.html"},
{title: " Cafune", tag:['all', 'serenist'],img: "images/card28.jpeg",link: "page1.html"},
{title: " Kaamos", tag:['all', 'healer'],img: "images/card29.jpeg",link: "page1.html"},
{title: " Sisu", tag:['all', 'healer'],img: "images/card30.jpeg",link: "page1.html"},
{title: " Flaneur", tag:['all', 'healer'],img: "images/card31.jpeg",link: "page1.html"},
{title: " Depaysement", tag:['all', 'healer'],img: "images/card32.jpeg",link: "page1.html"},
{title: " Komorebi", tag:['all', 'healer'],img: "images/card33.jpeg",link: "page1.html"},
{title: " Quintessential", tag:['all', 'healer'],img: "images/card34.jpeg",link: "page1.html"},
{title: " Gigil", tag:['all', 'healer'],img: "images/card35.jpeg",link: "page1.html"},
{title: " Hyggelig", tag:['all', 'healer'],img: "images/card36.jpeg",link: "page1.html"},
{title: " Yugen", tag:['all', 'healer'],img: "images/card37.jpeg",link: "page1.html"},
{title: " Aubade", tag:['all', 'healer'],img: "images/card38.jpeg",link: "page1.html"},
{title: " Sonorous", tag:['all', 'healer'],img: "images/card39.jpeg",link: "page1.html"},
{title: " Jayus", tag:['all', 'healer'],img: "images/card40 (1).jpeg",link: "page1.html"},
{title: " Tingo", tag:['all', 'sculptist'],img: "images/card40 (3).jpeg",link: "page1.html"},
{title: " Hanyauku", tag:['all', 'sculptist'],img: "images/card40 (4).jpeg",link: "page1.html"},




];


